version: '3.8'
services:
  myapp-postgresql:
    image: postgres:13.2
    # volumes:
    #     - ~/volumes/jhipster/myapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
